version: '3'

services:
  main-app-1: &main-app
    build:
      context: .
      dockerfile: scatterbox.dev/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - scatterbox:latest
    image: scatterbox:latest
    environment:
      - FLASK_APP=api.py
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DEV_API_KEY=${DEV_API_KEY}
      - API_KEY=${API_KEY}
      - DBHOST=${DBHOST}
      - DBDATABASE=${DBDATABASE}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - site_dev_api_key=${site_dev_api_key}
      - VPN_detection_API_key=${VPN_detection_API_key}
      - ChatDbHost=${ChatDbHost}
      - ChatDbDatabase=${ChatDbDatabase}
      - ChatDbUser=${ChatDbUser}
      - ChatDbPassword=${ChatDbPassword}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - AI_MODERATION_API_KEY=${AI_MODERATION_API_KEY}
      - proxy=${proxy}
    volumes:
      - ./scatterbox.dev:/app
      - /var/Site-resources/logs/scatterbox.dev:/var/Site-resources/logs/scatterbox.dev
      - ./requirements.txt:/app/requirements.txt
    labels:
      - "traefik.http.routers.main-app.rule=Host(`scatterbox.dev`)"
      - "traefik.http.services.main-app.loadbalancer.server.port=3001"
  main-app-2:
    <<: *main-app

  main-app-3:
    <<: *main-app

  gelblaster:
    build:
      context: .
      dockerfile: gelblast.scatterbox.dev/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      cache_from:
        - gelblaster:latest
    image: gelblaster:latest
    environment:
      - FLASK_APP=app.py
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./gelblast.scatterbox.dev:/app
      - sqlite_data:/app/instance
      - ./requirements.txt:/app/requirements.txt
    labels:
      - "traefik.http.routers.gelblaster.rule=Host(`gelblast.scatterbox.dev`)"
      - "traefik.http.services.gelblaster.loadbalancer.server.port=3004"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
      - MYSQL_DATABASE=${DBDATABASE}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.scatterbox.dev`)"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/api/version"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
  sqlite_data:
